### ISSUE TITLE
Don't hide with CSS then display with JS?

### ISSUE THREAD

**Issue by mrspeaker** [a13o/disengaged#6]
I have joined the growing army (there are dozens of us... dozens!) of people who heavily use NoScript for browsing the web (I'm sure there's a healthy crossover of those dozen people who would like Disengaged too). This means that by default JavaScript is not enabled on social sites. Hacker News, Twitter, and Reddit all (amazingly) work without requiring JavaScript - so I don't whitelist them.

With Disegaged on Hacker News, the child comments are hidden via CSS and then toggle-able via JavaScript. To see any child comments it's necessary to whitelist the site with NoScript.

This feels a bit wrong to me - it seems that if something is displayed via JS then it should also be hidden via JS so it is consistent.

Alternatively, there could be some per-site options - but this may go against the Disengaged manifesto!

**Comment by a13o** [comment]
I definitely don't want to break any sites, which this feels similar to doing. I will try using HN with JS disabled and see what the experience is like.

In your view, which of these options are preferred from this extension?
1. HN comments are folded in accordance with the extension's principles, but you have to toggle the plugin off (which necessitates a page refresh) whenever you want to unfold one.
1. HN comments are simply unfolded for NoScript users, because they were never folded in the first place.

I unfurl an HN comment here and there myself, especially in replies to my own comments, and you did take the time to write up this issue so I suspect I know which is preferred. Just making sure that toggling the plugin is not an ergonomic workaround so I can rule it out.

While there may be options someday, the order of implementation would be opt-in/opt-out at the site level, and then global opt-in/opt-out for rules in the [Code of Ethics](https://github.com/a13o/disengaged/blob/master/CODE_OF_ETHICS.md). E.g. opt-out of all `A.2` enforcement. I don't want to do per rule per site, because heavy configuration is always a design smell to me.

**Comment by mrspeaker** [comment]
I think it's ok to mandate JavaScript. Noscript-ers are probably still a tiny demographic (at least, for now ;) ) so it might be better to just leave it as-is. For hackernews, I'm thought I wanted to see replies (I was more against B1 than A2) - but having used it for a couple of days now, I really can see the value in ignoring replies! I just wish it didn't need JavaScript... but so be it.

I do think that "show-the-same-way-you-hide" is a good mantra (one that is ignored by a lot of website authors who show page-load spinners by default, and then remove them with JavaScript: leaving a page filled with spinners that *look like* they are doing things, when they aren't).

I also agree with your less-configuration stance: it's a path to make Disengaged useless. So, i'm going to close this and just whitelist HackerNews when i realllly want to read a reply.
